// app/layout.js
import { ToastContainer } from 'react-toastify';
import './globals.css';
import ReduxProvider from './Redux/ReduxProvider';

export const metadata = {
  title: 'MERN CRUD',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add the favicon link here */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ToastContainer/>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
